export const WS_SERVER_MESSAGE_TYPES = {
  CONNECTED: 'CONNECTED',
  COMBOS_UPDATE: 'COMBOS_UPDATE',
  PLAYER_LIST_UPDATE: 'PLAYER_LIST_UPDATE',
}

export const WS_CLIENT_MESSAGE_TYPES = {
  LOGIN: 'LOGIN',
  NEW_COMBO_DATA: 'NEW_COMBO_DATA',
  COMBO_ENDED: 'COMBO_ENDED' // ?
}
