export const TOAST_EVENT_TYPES = {
  MAP_HIGHSCORES: 'MAP_HIGHSCORES',
  NEW_BEST_SCORE: 'NEW_BEST_SCORE',
  NEW_MAP_DETECTED: 'NEW_MAP_DETECTED',
}

export const HIGHSCORE_PEEK_TYPES = {
  CURRENT_MAP: 'CURRENT_MAP',
  ALL_MAPS: 'ALL_MAPS'
}